### PR TITLE
Sqrt and Cbrt type synonyms

### PR DESCRIPTION
**Pull request by bjornbm**
I think these are about as worthy as Recip in terms of clarity versus namespace pollution.

### CODE REVIEW

**Comment by dmcclean** [comment]
Looks good. For consistency should we add the term level ones?

**Comment by bjornbm** [comment]
Yes. I'll do that. By the way at type level we have `Root` but the corresponding functions in TermLevel and Dimensional are called `nroot`. Do we want to stick with one?

**Comment by dmcclean** [comment]
Hmm. I'd say stick with it, because `root` might be confused for `sqrt`? But I don't feel strongly about it either way.

**Comment by bjornbm** [comment]
We could change TypeLevel to `NRoot`.

**Comment by dmcclean** [comment]
That sounds like a good plan, then we are consistent one way or the other.

**Pull request merged**
