### PR TITLE
Release 1.1 to Hackage

### PR DESCRIPTION
**Pull request by bjornbm**
In order to get the GHC 8.4 compatibility fixes from @varosi to Hackage …

Since we have a bunch of other (breaking) changes in the changelog. I plan to publish version 1.1 in a day or two. @dmcclean: do you see any reason to **not** publish the changes in master? Do they warrant a version 2.0 instead of 1.1?

### CODE REVIEW

**Comment by bjornbm** [comment]
It seems the Travis CI errors are timeouts etc. Not sure why. Is there a way to force a retest without a new git push?

**Comment by dmcclean** [comment]
@bjornbm from the Travis webpage you can restart the checks, I will do so now.

**Comment by bjornbm** [comment]
Thanks @dmcclean. I was looking for a button to retest but couldn't find one. I guess I'll look harder next time! :)

**Comment by bjornbm** [comment]
Merged and uploaded to hackage.

**Pull request merged**
