### PR TITLE
Add percent as a unit

### PR DESCRIPTION
**Pull request by dmcclean**
Here's the definition of percent to play around with and see if we like it.

### CODE REVIEW

**Comment by dmcclean** [comment]
````
> putStrLn $ showIn percent (_3)
300.0 %
> putStrLn $ showIn percent (0.37 *~ one)
37.0 %
> putStrLn $ showIn (percent * percent) (0.37 *~ one)
3700.0 % %
````

**Comment by bjornbm** [comment]
Thanks, the `3700 % %` doesn't look too great but I guess if that is what you ask for…

**Comment by dmcclean** [comment]
Yeah, you get what you ask for, but I do think that some kind of opt-in warning system will be nice for dynamic uses.

**Comment by bjornbm** [comment]
Do you want to add this, too, in the next release, or did you want to play with it more first? I'm fine with merging it.

**Comment by dmcclean** [comment]
I have lingering doubts about it, but it seems useful enough for my controls work to be worth it. Merging.

**Comment by bjornbm** [comment]
If we decided to have `percent` how about also adding `permille` (‰) and `permyriad` (‱)? Granted they are less common but won't break anything not already broken by %.

**Comment by dmcclean** [comment]
Fine by me. I don't think I object to obscure or disused units, only
ill-defined ones or ones with dimensions we don't model well.

**Pull request merged**
