### PR TITLE
Added BTU to NonSI

### PR DESCRIPTION
**Pull request by albertov**

### CODE REVIEW

**Comment by dmcclean** [comment]
I don't have a problem adding this, but if we do add it with this UCUM name, I think we need to use the UCUM value for it. That would be 1.054350 kJ, which is slightly less than the value here.

They actually define 6 flavors of BTU (the Wikipedia page has 8). The value in this pull request is closest to the one labeled "international table British thermal unit" by the UCUM, which Wikipedia says is the most commonly used, and which UCUM assigned the code `[Btu_IT]`, so if you need this value we may want to implement all the flavors?

**Comment by dmcclean** [comment]
Also, my apologies for the mis-typesetting of your name in the latest HCAR. I goofed up in the LaTeX file and didn't notice it in the draft report.

**Comment by dmcclean** [comment]
Worse, the UCUM's values don't quite agree with Wikipedia's.

UCUM:

| name | dimension | print | c/s | c/i | M | definition |  |
| --- | --- | --- | --- | --- | --- | --- | --- |
| British thermal unit at 39 °F | energy | Btu39°F | [Btu_39] | [BTU_39] | no | 1.05967 | kJ |
| British thermal unit at 59 °F | energy | Btu59°F | [Btu_59] | [BTU_59] | no | 1.05480 | kJ |
| British thermal unit at 60 °F | energy | Btu60°F | [Btu_60] | [BTU_60] | no | 1.05468 | kJ |
| mean British thermal unit | energy | Btum | [Btu_m] | [BTU_M] | no | 1.05587 | kJ |
| international table British thermal unit | energy | BtuIT | [Btu_IT] | [BTU_IT] | no | 1.05505585262 | kJ |
| thermochemical British thermal unit | energy | Btuth | [Btu_th] | [BTU_TH] | no | 1.054350 | kJ |

Wikipedia:

wikipedia-table

**Comment by dmcclean** [comment]
@albertov Could you clarify the source of the value you used, `0.293071 *~ watt * hour`?

**Comment by albertov** [comment]
@dmcclean Sorry for the delay, I've been on vacations. I got that constant from Wikipedia, although not in that exact form but as "1000 BTU/h is approximately 293.071 W".

screen shot 2016-01-13 at 14 19 47

**Comment by dmcclean** [comment]
So that seems closest to the one they label the "international table British thermal unit", which UCUM calls `[Btu_IT]`.

Are you OK with using the value `1.05505585262 *~ kilo joule` instead? It's only a relative difference of 2.4e-7, so I can't imagine it matters, but it will be compliant with the UCUM spec then.

If so I'll make a new patch to add all 6 flavors.

**Comment by albertov** [comment]
@dmcclean I'm ok with that value, it won't be noticeable at all in our application. BTW, I made the pull request before seeing that `mkUnitQ` and `atom` are exported by Dimensional since I thought there was no way of adding custom units without a PR. I now have `btu` inside my project so perhaps it doesn't need to go inside `NonSI` anymore since there won't be space to accommodate all the non SI units lying around :)

**Comment by dmcclean** [comment]
Ahh, indeed. I am writing a user manual, I will be sure to make a note in it of how to add custom units.

We're in favor of adding it anyway, just to make things easier for people. There are a billion crazy units floating around and we definitely won't ever add them all, but this one is still widely used (unfortunately, since there are competing definitions) in a lot of circles.

**Comment by dmcclean** [comment]
Thanks very much, @albertov. This has just been merged with the value we discussed, so it will make it in to the upcoming 1.1 release.

**Pull request merged**
