### PR TITLE
Application of patches from #194

### PR DESCRIPTION
**Pull request by bjornbm**
Will merge with successful Travis build.

### CODE REVIEW

**Comment by bjornbm** [comment]
LTS-2 fails with:

    Could not find module ‘Data.Kind’

LTS-10 fails with:

    doctest: unrecognized option `-XNoStarIsType'

**Comment by bjornbm** [comment]
Now builds on GHC ≥ 8 (when Data.Kind module was introduced). Are we ready to drop support for GHC 7.* or do we have to work around the Data.Kind imports?

**Comment by peti** [comment]
Yes, please merge these fixes! GHC 7.10.3 was released ~3 years ago and I am perfectly happy to see support for it drop if that means we'll get support for *recent versions*  of the compiler.

**Comment by bjornbm** [comment]
Yes, the Idea was not whether to support current GHC but whether to convolute the code with ifdefs or other mechanisms to maintain support for GHC 7. As for myself I am OK to drop GHC 7. Will merge this coming week unless @dmcclean objects.

**Comment by bjornbm** [comment]
FYI I cannot yet deploy to hackage due to haskell/hackage-server#788.

**Pull request merged**
