### PR TITLE
Support for GHC 7.10.3 up to GHC 8.4.1 with adding Semigroup instance

### PR DESCRIPTION
**Pull request by varosi**
Built and tested

### CODE REVIEW

**Comment by bjornbm** [comment]
Thanks @varosi. Looks good to me. Will give @dmcclean a chance to look before I merge. If he doesn't object of merge by tomorrow I will merge this.

As a side note we should also add more travis test cases, including your ghc84 one.

**Comment by varosi** [comment]
I have added changes for Travis to test with.

**Comment by varosi** [comment]
> libtinfo.so.6: cannot open shared object file: No such file or directory

I think that somehow we have to install this library on Travis, but I don't have much experiance with it. @bjornbm, could you help on that? All other compilers seems to work fine there. I already tested all of them locally on my Windows 10.

**Comment by bjornbm** [comment]
Thanks again. I took a quick look and [this looks relevant](https://bugs.launchpad.net/ubuntu/+source/ncurses/+bug/259139). I'm not familiar with Travis CI though (@dmcclean set it up for us) and don't have time to investigate more right now. I propose to comment out the GHC 8.4 line in `.travis.yml` for now and open a new issue to investigate.

**Comment by varosi** [comment]
Thanks!

**Comment by dmcclean** [comment]
Awesome, thanks @varosi and @bjornbm!

**Pull request merged**
